---

- hosts: myclients
  become: yes
  gather_facts: no
  vars:
    - day1: Sunday
    - day2: Monday
  tasks:
    - name: print
      command: echo "{{ day1 }} is over it's {{ day2 }} already!.The os family is {{ ansible_os_family }}"
      
